### ISSUE TITLE
Issue while Installing

### ISSUE THREAD

**Issue by chikme01** [bk-cs/PSFalcon#11]
Hello,

I see an issue while I try to install this module
Can you please help? Below is the error:

_WARNING: Source Location 'https://www.powershellgallery.com/api/v2/package/PSFalcon/1.2.2' is not valid.
PackageManagement\Install-Package : Package 'PSFalcon' failed to download.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.1.2\PSModule.psm1:9349 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Users\Admini...con.1.2.2.nupkg:String) [Install-Package], Exception
    + FullyQualifiedErrorId : PackageFailedInstallOrDownload,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage_

**Comment by bk-cs** [comment]
Hi chikme01,

Have you tried running 'Install-Module -Name PSFalcon'? That's typically how I perform the installations, and it looks like you're doing something different here. 

Any additional context would be helpful in troubleshooting the error that you're running into.

Thanks!

**Comment by chikme01** [comment]
Hello bk-cs,

Yes, I am using the exact same command.
Let me send a screenshot in few minutes

Thanks
Megha

**Comment by chikme01** [comment]
Here is a screenshot - if that helps

[image: image.png]

**Comment by bk-cs** [comment]
The screenshot doesn't come through the GitHub post. 

According to a forum post, this error has been seen due to connectivity problems with the PSGallery:
https://powershell.org/forums/topic/failed-to-downloadinstall-module/

If it doesn't work when you retry and/or use a different internet connection, try doing a manual installation by downloading the GitHub repository, unzipping it, and placing it in your $PSHOME\Modules folder under 'PSFalcon'.

Please note that this will cause you to get the latest version, which has commands that are currently being added under the 'firewall-management' and 'iocs' sections, so don't expect those to work quite yet.

**Comment by chikme01** [comment]
Thanks much.
I manually downloaded and imported.
After I changed the execution policy, Inwas successfully able see the
modules

Thank you

Thanks
Megha
