### ISSUE TITLE
Get-CsHostId offset

### ISSUE THREAD

**Issue by Davelicious** [bk-cs/PSFalcon#22]
I get {@{code=400; message=Bad request}} errors whenever I'm using the offset parameter with Get-CsHostId

ex
PS C:\> Get-CsHostId -Offset 2 -Limit 11
meta                                                                                            resources errors                            
----                                                                                            --------- ------                            
@{query_time=0,001980023; powered_by=device-api; trace_id=xxx-xxx-xxx-xxx-xxx} {}        {@{code=400; message=Bad request}}

PS C:\> Get-CsHostId -Offset 2

meta                                                                                            resources errors                            
----                                                                                            --------- ------                            
@{query_time=0,002142376; powered_by=device-api; trace_id=xxx-xxx-xxx-xxx-xxx} {}        {@{code=400; message=Bad request}}

**Comment by bk-cs** [comment]
Hi Davelicious,

The Get-CsHostId command uses a token-based offset, because it uses the /devices/queries/devices-scroll/v1 endpoint. You can't manually set the offset, but you can use the -All parameter to retrieve multiple results.

For instance, if you wanted all results, you could do "Get-CsHostId -All", or if you wanted to get all results for a particular filter; "Get-CsHostId -Filter "hostname:'example'" -All".
