### ISSUE TITLE
Policies not being returned with get-cshostinfo.

### ISSUE THREAD

**Issue by Rogueit** [bk-cs/PSFalcon#26]
When pulling the information from crowdstrike for host ids with:
Get-CsHostInfo -id 7xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx7

the device policies comes back like this instead of pulling the actual policy for the device.
"device_policies":  "@{prevention=; sensor_update=; device_control=; global_config=; remote_response=; firewall=}",

**Comment by bk-cs** [comment]
Hi Rogueit,

What sort of information are you looking for?

There is device policy information that is returned in the Device API call (Get-CsHostInfo), but it's contained within an array, which is why you're seeing "@{}". In order to see the contents of that, you need to save the results and drill down into the response object.

$Result = Get-CsHostInfo -Id xxx
$Result.resources.device_policies

You can go down even deeper inside device_policies too:
$Result.resources.device_policies.prevention

If you're having trouble figuring out how to navigate it, sometimes it's easier to view the entire result as a string:
$Result | ConvertTo-Json -Depth 64
