### ISSUE TITLE
Get-CsSensorBuild platform error

### ISSUE THREAD

**Issue by Jihsei** [bk-cs/PSFalcon#30]
Hi there,
The platform parameter value is not correct according to the query response even though the string is correct.
The error I get is: @{code=400; message=Query string parameter 'platform' is not an allowable value}

**Comment by bk-cs** [comment]
Hi Jihsei,

This looks like something that is specific to the API itself, not PSFalcon. Can you post an example of the command you're trying to run?

Thanks!

**Comment by Jihsei** [comment]
Hello there,

The command is simply "Get-CsSensorBuild -Platform Windows" but the result is the same for all platforms.

**Comment by bk-cs** [comment]
Thanks! The issue is that this API (and many others) are case sensitive. In my testing, the following works without issue:

Get-CsSensorBuild -Platform windows

In PSFalcon v2 (release TBD, but soon) I'll enforce lower case values to avoid this issue. Please let me know if this doesn't solve your problem!
